apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: product-ingress
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    type: HTTP
    requestPath: /healthz # Adjust this to match your actual health check path
    port: 80