apiVersion: v1
kind: Service
metadata:
  name: sales-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "product-ingress"}' # Reference to the BackendConfig
spec:
  type: NodePort
  selector:
    app: sales
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80