apiVersion: apps/v1 
kind: Deployment
metadata:
  name: product 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: product 
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: asia-east1-docker.pkg.dev/ikala-cloud-swe-dev-sandbox/ann-test/product:v18
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "10Mi"
            cpu: "10m"
          requests:
            memory: "5Mi"
            cpu: "5m"
        env: 
          - name: POSTGRES_HOST
            value: pgsql  # The hostname of your PostgreSQL service (serviceName in StatefulSet)
          - name: POSTGRES_PORT
            value: "5432"  # The port on which PostgreSQL is running
          - name: POSTGRES_DB
            value: ann  # The name of your PostgreSQL database
          - name: POSTGRES_USER
            value: ann  # The username for connecting to PostgreSQL
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql
                key: POSTGRES_PASSWORD  # Reference to the Secret for PostgreSQL password
